runtime: nodejs10

handlers:

# Routing for Javacript to serve directly
- url: /(.+\.js)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

  # To load images
- url: /(.+\.png)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

  # To load eot files for font awesome
- url: /(.+\.eot)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

   # To load svg files for font awesome
- url: /(.+\.svg)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

  # To load woff2 files for font awesome
- url: /(.+\.woff2)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

    # To load ttf files for font awesome
- url: /(.+\.ttf)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

      # To load woff files for font awesome
- url: /(.+\.woff)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

# Routing for a prod styles.css to serve directly
- url: /(.+\.css)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

# Routing for typedoc, assets and favicon.ico to serve directly
- url: /((?:assets|docs)/.*|favicon\.ico)
  static_files: dist/cti-v2/\1
  upload: dist/cti-v2/.*

# Use index.html for everything else.
- url: /
  static_files: dist/cti-v2/index.html
  upload: dist/cti-v2/index.html

- url: /.*
  static_files: dist/cti-v2/index.html
  upload: dist/cti-v2/index.html